var searchData=
[
  ['has_5fdependency_0',['has_dependency',['../classMeltPoolDG_1_1Material.html#aeda2dcbef1ccce4da92d11cb7f51444c',1,'MeltPoolDG::Material']]],
  ['has_5ffrom_5fstring_1',['has_from_string',['../structdealii_1_1Patterns_1_1Tools_1_1has__from__string.html',1,'dealii::Patterns::Tools']]],
  ['has_5fto_5fstring_2',['has_to_string',['../structdealii_1_1Patterns_1_1Tools_1_1has__to__string.html',1,'dealii::Patterns::Tools']]],
  ['has_5fvalues_3',['has_values',['../structdealii_1_1Patterns_1_1Tools_1_1has__values.html',1,'dealii::Patterns::Tools']]],
  ['heat_4',['heat',['../structMeltPoolDG_1_1Parameters.html#a2f7b1ebc6c673242cc9e7e93ac027f0f',1,'MeltPoolDG::Parameters']]],
  ['heat_5fcut_5foperation_2ecpp_5',['heat_cut_operation.cpp',['../heat__cut__operation_8cpp.html',1,'']]],
  ['heat_5fcut_5foperation_2ehpp_6',['heat_cut_operation.hpp',['../heat__cut__operation_8hpp.html',1,'']]],
  ['heat_5fcut_5foperator_2ecpp_7',['heat_cut_operator.cpp',['../heat__cut__operator_8cpp.html',1,'']]],
  ['heat_5fcut_5foperator_2ehpp_8',['heat_cut_operator.hpp',['../heat__cut__operator_8hpp.html',1,'']]],
  ['heat_5fdata_2ecpp_9',['heat_data.cpp',['../heat__data_8cpp.html',1,'']]],
  ['heat_5fdata_2ehpp_10',['heat_data.hpp',['../heat__data_8hpp.html',1,'']]],
  ['heat_5fdiffuse_5foperation_2ecpp_11',['heat_diffuse_operation.cpp',['../heat__diffuse__operation_8cpp.html',1,'']]],
  ['heat_5fdiffuse_5foperation_2ehpp_12',['heat_diffuse_operation.hpp',['../heat__diffuse__operation_8hpp.html',1,'']]],
  ['heat_5fdiffuse_5foperator_2ecpp_13',['heat_diffuse_operator.cpp',['../heat__diffuse__operator_8cpp.html',1,'']]],
  ['heat_5fdiffuse_5foperator_2ehpp_14',['heat_diffuse_operator.hpp',['../heat__diffuse__operator_8hpp.html',1,'']]],
  ['heat_5fevapor_5fcoupling_15',['heat_evapor_coupling',['../classMeltPoolDG_1_1MeltPool_1_1MeltPoolProblem.html#aef13bd4665df991c887e9ba0d2bce6f1',1,'MeltPoolDG::MeltPool::MeltPoolProblem']]],
  ['heat_5foperation_5fbase_2ehpp_16',['heat_operation_base.hpp',['../heat__operation__base_8hpp.html',1,'']]],
  ['heat_5ftransfer_5fproblem_2ecpp_17',['heat_transfer_problem.cpp',['../heat__transfer__problem_8cpp.html',1,'']]],
  ['heat_5ftransfer_5fproblem_2ehpp_18',['heat_transfer_problem.hpp',['../heat__transfer__problem_8hpp.html',1,'']]],
  ['heatcutoperation_19',['heatcutoperation',['../classMeltPoolDG_1_1Heat_1_1HeatCutOperation.html',1,'MeltPoolDG::Heat::HeatCutOperation&lt; dim &gt;'],['../classMeltPoolDG_1_1Heat_1_1HeatCutOperation.html#acc56dc653ce12f2896dbeb95606e2219',1,'MeltPoolDG::Heat::HeatCutOperation::HeatCutOperation()']]],
  ['heatcutoperator_20',['heatcutoperator',['../classMeltPoolDG_1_1Heat_1_1HeatCutOperator.html#a663eaa0ef447db0965c2212dd820881c',1,'MeltPoolDG::Heat::HeatCutOperator::HeatCutOperator()'],['../classMeltPoolDG_1_1Heat_1_1HeatCutOperator.html',1,'MeltPoolDG::Heat::HeatCutOperator&lt; dim, number &gt;']]],
  ['heatdata_21',['heatdata',['../structMeltPoolDG_1_1Heat_1_1HeatData.html',1,'MeltPoolDG::Heat::HeatData&lt; number &gt;'],['../structMeltPoolDG_1_1Heat_1_1HeatData.html#a31b2ea54fcb08e1c9fdf2564188bd162',1,'MeltPoolDG::Heat::HeatData::HeatData()']]],
  ['heatdata_3c_20double_20_3e_22',['HeatData&lt; double &gt;',['../structMeltPoolDG_1_1Heat_1_1HeatData.html',1,'MeltPoolDG::Heat']]],
  ['heatdata_3c_20number_20_3e_23',['HeatData&lt; number &gt;',['../structMeltPoolDG_1_1Heat_1_1HeatData.html',1,'MeltPoolDG::Heat']]],
  ['heatdiffusemultiphaseoperator_24',['heatdiffusemultiphaseoperator',['../classMeltPoolDG_1_1Heat_1_1HeatDiffuseMultiPhaseOperator.html#a30c139612a946947300fed29337643b1',1,'MeltPoolDG::Heat::HeatDiffuseMultiPhaseOperator::HeatDiffuseMultiPhaseOperator()'],['../classMeltPoolDG_1_1Heat_1_1HeatDiffuseMultiPhaseOperator.html',1,'MeltPoolDG::Heat::HeatDiffuseMultiPhaseOperator&lt; dim, number &gt;']]],
  ['heatdiffuseoperation_25',['heatdiffuseoperation',['../classMeltPoolDG_1_1Heat_1_1HeatDiffuseOperation.html#a6c350d45cf5e06bae9ee7b23d93e9ac8',1,'MeltPoolDG::Heat::HeatDiffuseOperation::HeatDiffuseOperation()'],['../classMeltPoolDG_1_1Heat_1_1HeatDiffuseOperation.html',1,'MeltPoolDG::Heat::HeatDiffuseOperation&lt; dim &gt;']]],
  ['heatoperationbase_26',['HeatOperationBase',['../classMeltPoolDG_1_1Heat_1_1HeatOperationBase.html',1,'MeltPoolDG::Heat']]],
  ['heattransferproblem_27',['heattransferproblem',['../classMeltPoolDG_1_1Heat_1_1HeatTransferProblem.html',1,'MeltPoolDG::Heat::HeatTransferProblem&lt; dim &gt;'],['../classMeltPoolDG_1_1Heat_1_1HeatTransferProblem.html#a6897890a5cfae93110c3e0c3630fb1cd',1,'MeltPoolDG::Heat::HeatTransferProblem::HeatTransferProblem()']]],
  ['heaviside_28',['heaviside',['../namespaceMeltPoolDG_1_1UtilityFunctions.html#aba5388657cac84bee12153cacd979c2c',1,'MeltPoolDG::UtilityFunctions::heaviside(const number in, const number limit=0.0)'],['../namespaceMeltPoolDG_1_1UtilityFunctions.html#a0e832ec71d2b32a269f08a7d8734b5ae',1,'MeltPoolDG::UtilityFunctions::heaviside(const std::vector&lt; number &gt; in, const number limit=0.0)'],['../namespaceMeltPoolDG_1_1UtilityFunctions.html#afc9df12b7bc3fff5ac305917e996d263',1,'MeltPoolDG::UtilityFunctions::heaviside(const VectorizedArray&lt; number &gt; &amp;in, const number limit=0.0)'],['../namespaceMeltPoolDG_1_1UtilityFunctions_1_1CharacteristicFunctions.html#a5dfb142bb4d754328207f94ff3160823',1,'MeltPoolDG::UtilityFunctions::CharacteristicFunctions::heaviside()']]],
  ['heavy_5fphase_5fweight_29',['heavy_phase_weight',['../structMeltPoolDG_1_1LevelSet_1_1DeltaApproximationPhaseWeightedData.html#a2b706f6215197ceacbb1cb55ad2f8063',1,'MeltPoolDG::LevelSet::DeltaApproximationPhaseWeightedData']]],
  ['heavy_5fphase_5fweight_5f2_30',['heavy_phase_weight_2',['../structMeltPoolDG_1_1LevelSet_1_1DeltaApproximationPhaseWeightedData.html#ae6e38c1472c796dc56d945f6f0bf9ddd',1,'MeltPoolDG::LevelSet::DeltaApproximationPhaseWeightedData']]],
  ['helmholtz_5fdg_5foperator_2ecpp_31',['helmholtz_DG_operator.cpp',['../helmholtz__DG__operator_8cpp.html',1,'']]],
  ['helmholtz_5fdg_5foperator_2ehpp_32',['helmholtz_DG_operator.hpp',['../helmholtz__DG__operator_8hpp.html',1,'']]],
  ['helmholtzdgoperator_33',['helmholtzdgoperator',['../classMeltPoolDG_1_1LevelSet_1_1HelmholtzDGOperator.html',1,'MeltPoolDG::LevelSet::HelmholtzDGOperator&lt; dim, Number &gt;'],['../classMeltPoolDG_1_1LevelSet_1_1HelmholtzDGOperator.html#ab57c27b7582bb23bee92488dcd8d35bd',1,'MeltPoolDG::LevelSet::HelmholtzDGOperator::HelmholtzDGOperator()']]],
  ['helmholtzdgoperator_3c_20dim_2c_20double_20_3e_34',['HelmholtzDGOperator&lt; dim, double &gt;',['../classMeltPoolDG_1_1LevelSet_1_1HelmholtzDGOperator.html',1,'MeltPoolDG::LevelSet']]],
  ['hessian_35',['hessian',['../classdealii_1_1Functions_1_1ChangedSignFunction.html#a3f51609258b5bc386507326e14707e0d',1,'dealii::Functions::ChangedSignFunction']]]
];
