var searchData=
[
  ['has_5fdependency_0',['has_dependency',['../classMeltPoolDG_1_1Material.html#aeda2dcbef1ccce4da92d11cb7f51444c',1,'MeltPoolDG::Material']]],
  ['has_5ffrom_5fstring_1',['has_from_string',['../structdealii_1_1Patterns_1_1Tools_1_1has__from__string.html',1,'dealii::Patterns::Tools']]],
  ['has_5fto_5fstring_2',['has_to_string',['../structdealii_1_1Patterns_1_1Tools_1_1has__to__string.html',1,'dealii::Patterns::Tools']]],
  ['has_5fvalues_3',['has_values',['../structdealii_1_1Patterns_1_1Tools_1_1has__values.html',1,'dealii::Patterns::Tools']]],
  ['heat_4',['heat',['../structMeltPoolDG_1_1Heat_1_1HeatTransferCaseParameters.html#a4a96ab0ff5d57c87cee18b9b67029a09',1,'MeltPoolDG::Heat::HeatTransferCaseParameters::heat'],['../structMeltPoolDG_1_1Parameters.html#a2f7b1ebc6c673242cc9e7e93ac027f0f',1,'MeltPoolDG::Parameters::heat']]],
  ['heat_5fcut_5foperation_2ecpp_5',['heat_cut_operation.cpp',['../heat__cut__operation_8cpp.html',1,'']]],
  ['heat_5fcut_5foperation_2ehpp_6',['heat_cut_operation.hpp',['../heat__cut__operation_8hpp.html',1,'']]],
  ['heat_5fcut_5foperator_2ecpp_7',['heat_cut_operator.cpp',['../heat__cut__operator_8cpp.html',1,'']]],
  ['heat_5fcut_5foperator_2ehpp_8',['heat_cut_operator.hpp',['../heat__cut__operator_8hpp.html',1,'']]],
  ['heat_5fdata_2ecpp_9',['heat_data.cpp',['../heat__data_8cpp.html',1,'']]],
  ['heat_5fdata_2ehpp_10',['heat_data.hpp',['../heat__data_8hpp.html',1,'']]],
  ['heat_5fdiffuse_5foperation_2ecpp_11',['heat_diffuse_operation.cpp',['../heat__diffuse__operation_8cpp.html',1,'']]],
  ['heat_5fdiffuse_5foperation_2ehpp_12',['heat_diffuse_operation.hpp',['../heat__diffuse__operation_8hpp.html',1,'']]],
  ['heat_5fdiffuse_5foperator_2ecpp_13',['heat_diffuse_operator.cpp',['../heat__diffuse__operator_8cpp.html',1,'']]],
  ['heat_5fdiffuse_5foperator_2ehpp_14',['heat_diffuse_operator.hpp',['../heat__diffuse__operator_8hpp.html',1,'']]],
  ['heat_5fevapor_5fcoupling_15',['heat_evapor_coupling',['../classMeltPoolDG_1_1MeltPool_1_1MeltPoolProblem.html#ad509ed4c9132fb3ae3d89246295eb607',1,'MeltPoolDG::MeltPool::MeltPoolProblem']]],
  ['heat_5foperation_5fbase_2ehpp_16',['heat_operation_base.hpp',['../heat__operation__base_8hpp.html',1,'']]],
  ['heat_5ftransfer_5fcase_2ehpp_17',['heat_transfer_case.hpp',['../heat__transfer__case_8hpp.html',1,'']]],
  ['heat_5ftransfer_5fproblem_2ecpp_18',['heat_transfer_problem.cpp',['../heat__transfer__problem_8cpp.html',1,'']]],
  ['heat_5ftransfer_5fproblem_2ehpp_19',['heat_transfer_problem.hpp',['../heat__transfer__problem_8hpp.html',1,'']]],
  ['heatcutoperation_20',['heatcutoperation',['../classMeltPoolDG_1_1Heat_1_1HeatCutOperation.html',1,'MeltPoolDG::Heat::HeatCutOperation&lt; dim &gt;'],['../classMeltPoolDG_1_1Heat_1_1HeatCutOperation.html#acc56dc653ce12f2896dbeb95606e2219',1,'MeltPoolDG::Heat::HeatCutOperation::HeatCutOperation()']]],
  ['heatcutoperator_21',['heatcutoperator',['../classMeltPoolDG_1_1Heat_1_1HeatCutOperator.html',1,'MeltPoolDG::Heat::HeatCutOperator&lt; dim, number &gt;'],['../classMeltPoolDG_1_1Heat_1_1HeatCutOperator.html#a663eaa0ef447db0965c2212dd820881c',1,'MeltPoolDG::Heat::HeatCutOperator::HeatCutOperator()']]],
  ['heatdata_22',['heatdata',['../structMeltPoolDG_1_1Heat_1_1HeatData.html#a31b2ea54fcb08e1c9fdf2564188bd162',1,'MeltPoolDG::Heat::HeatData::HeatData()'],['../structMeltPoolDG_1_1Heat_1_1HeatData.html',1,'MeltPoolDG::Heat::HeatData&lt; number &gt;']]],
  ['heatdata_3c_20double_20_3e_23',['HeatData&lt; double &gt;',['../structMeltPoolDG_1_1Heat_1_1HeatData.html',1,'MeltPoolDG::Heat']]],
  ['heatdata_3c_20number_20_3e_24',['HeatData&lt; number &gt;',['../structMeltPoolDG_1_1Heat_1_1HeatData.html',1,'MeltPoolDG::Heat']]],
  ['heatdiffusemultiphaseoperator_25',['heatdiffusemultiphaseoperator',['../classMeltPoolDG_1_1Heat_1_1HeatDiffuseMultiPhaseOperator.html',1,'MeltPoolDG::Heat::HeatDiffuseMultiPhaseOperator&lt; dim, number &gt;'],['../classMeltPoolDG_1_1Heat_1_1HeatDiffuseMultiPhaseOperator.html#a30c139612a946947300fed29337643b1',1,'MeltPoolDG::Heat::HeatDiffuseMultiPhaseOperator::HeatDiffuseMultiPhaseOperator()']]],
  ['heatdiffuseoperation_26',['heatdiffuseoperation',['../classMeltPoolDG_1_1Heat_1_1HeatDiffuseOperation.html',1,'MeltPoolDG::Heat::HeatDiffuseOperation&lt; dim &gt;'],['../classMeltPoolDG_1_1Heat_1_1HeatDiffuseOperation.html#a6c350d45cf5e06bae9ee7b23d93e9ac8',1,'MeltPoolDG::Heat::HeatDiffuseOperation::HeatDiffuseOperation()']]],
  ['heatoperationbase_27',['HeatOperationBase',['../classMeltPoolDG_1_1Heat_1_1HeatOperationBase.html',1,'MeltPoolDG::Heat']]],
  ['heattransfercase_28',['heattransfercase',['../classMeltPoolDG_1_1Heat_1_1HeatTransferCase.html#aa6e9b054cf295b691cdc629da7198fd9',1,'MeltPoolDG::Heat::HeatTransferCase::HeatTransferCase()'],['../classMeltPoolDG_1_1Heat_1_1HeatTransferCase.html',1,'MeltPoolDG::Heat::HeatTransferCase&lt; dim &gt;']]],
  ['heattransfercaseparameters_29',['HeatTransferCaseParameters',['../structMeltPoolDG_1_1Heat_1_1HeatTransferCaseParameters.html',1,'MeltPoolDG::Heat']]],
  ['heattransfercaseparameters_3c_20double_20_3e_30',['HeatTransferCaseParameters&lt; double &gt;',['../structMeltPoolDG_1_1Heat_1_1HeatTransferCaseParameters.html',1,'MeltPoolDG::Heat']]],
  ['heattransferproblem_31',['heattransferproblem',['../classMeltPoolDG_1_1Heat_1_1HeatTransferProblem.html#a01c01d29532abc82365343768b1b63eb',1,'MeltPoolDG::Heat::HeatTransferProblem::HeatTransferProblem()'],['../classMeltPoolDG_1_1Heat_1_1HeatTransferProblem.html',1,'MeltPoolDG::Heat::HeatTransferProblem&lt; dim &gt;']]],
  ['heaviside_32',['heaviside',['../namespaceMeltPoolDG_1_1UtilityFunctions.html#aba5388657cac84bee12153cacd979c2c',1,'MeltPoolDG::UtilityFunctions::heaviside()'],['../namespaceMeltPoolDG_1_1UtilityFunctions_1_1CharacteristicFunctions.html#a5dfb142bb4d754328207f94ff3160823',1,'MeltPoolDG::UtilityFunctions::CharacteristicFunctions::heaviside()'],['../namespaceMeltPoolDG_1_1UtilityFunctions.html#a0e832ec71d2b32a269f08a7d8734b5ae',1,'MeltPoolDG::UtilityFunctions::heaviside(const std::vector&lt; number &gt; in, const number limit=0.0)'],['../namespaceMeltPoolDG_1_1UtilityFunctions.html#afc9df12b7bc3fff5ac305917e996d263',1,'MeltPoolDG::UtilityFunctions::heaviside(const VectorizedArray&lt; number &gt; &amp;in, const number limit=0.0)']]],
  ['heavy_5fphase_5fweight_33',['heavy_phase_weight',['../structMeltPoolDG_1_1LevelSet_1_1DeltaApproximationPhaseWeightedData.html#a2b706f6215197ceacbb1cb55ad2f8063',1,'MeltPoolDG::LevelSet::DeltaApproximationPhaseWeightedData']]],
  ['heavy_5fphase_5fweight_5f2_34',['heavy_phase_weight_2',['../structMeltPoolDG_1_1LevelSet_1_1DeltaApproximationPhaseWeightedData.html#ae6e38c1472c796dc56d945f6f0bf9ddd',1,'MeltPoolDG::LevelSet::DeltaApproximationPhaseWeightedData']]],
  ['helmholtz_5fdg_5foperator_2ecpp_35',['helmholtz_DG_operator.cpp',['../helmholtz__DG__operator_8cpp.html',1,'']]],
  ['helmholtz_5fdg_5foperator_2ehpp_36',['helmholtz_DG_operator.hpp',['../helmholtz__DG__operator_8hpp.html',1,'']]],
  ['helmholtzdgoperator_37',['helmholtzdgoperator',['../classMeltPoolDG_1_1LevelSet_1_1HelmholtzDGOperator.html#ab57c27b7582bb23bee92488dcd8d35bd',1,'MeltPoolDG::LevelSet::HelmholtzDGOperator::HelmholtzDGOperator()'],['../classMeltPoolDG_1_1LevelSet_1_1HelmholtzDGOperator.html',1,'MeltPoolDG::LevelSet::HelmholtzDGOperator&lt; dim, Number &gt;']]],
  ['helmholtzdgoperator_3c_20dim_2c_20double_20_3e_38',['HelmholtzDGOperator&lt; dim, double &gt;',['../classMeltPoolDG_1_1LevelSet_1_1HelmholtzDGOperator.html',1,'MeltPoolDG::LevelSet']]],
  ['hessian_39',['hessian',['../classdealii_1_1Functions_1_1ChangedSignFunction.html#a3f51609258b5bc386507326e14707e0d',1,'dealii::Functions::ChangedSignFunction']]],
  ['horizontallevelset_40',['horizontallevelset',['../classMeltPoolDG_1_1Simulation_1_1UnidirectionalHeatTransfer_1_1HorizontalLevelSet.html#a0d1656407009b8ede47e6ef671f8d7f1',1,'MeltPoolDG::Simulation::UnidirectionalHeatTransfer::HorizontalLevelSet::HorizontalLevelSet()'],['../classMeltPoolDG_1_1Simulation_1_1UnidirectionalHeatTransfer_1_1HorizontalLevelSet.html',1,'MeltPoolDG::Simulation::UnidirectionalHeatTransfer::HorizontalLevelSet&lt; dim &gt;']]]
];
