name: Install MeltPoolDG

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 0 * * 6' # run every Saturday at 00:00 UTC

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # Cancels any previous runs still in progress

jobs:
  build:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    name: Install MeltPoolDG
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmetis-dev libboost-all-dev
      - name: Compile MeltPoolDG
        run: |
          bash scripts/config/install.sh --nv
